### ISSUE TITLE
Multiple warnings "Restore cache failed: Dependencies file is not found"

### ISSUE THREAD

**Issue by sabre1041** [redhat-cop/github-workflows-operators#40]
Each job is creating the following warning:

```
Restore cache failed: Dependencies file is not found in <checkout_location>. Supported file pattern: go.sum
```

[setup-go@v4](https://github.com/actions/setup-go#v4) enables caching by default. We would want to review if this functionality satisfies how the workflow manages caching today.

**Comment by sabre1041** [comment]
im ok with option #2

**Comment by garethahealy** [comment]
https://github.com/redhat-cop/github-workflows-operators/pull/37
